### ISSUE TITLE
关于自定义回复的问题

### ISSUE THREAD

**Issue by simontombu** [hundun000/mirai-fleet-amiya#1]
说明中提及config\hundun.fleet.amiya\AmiyaChatFunction\ListenConfig.json中自定义回复的触发支持检测群消息是否包含关键词，给出的配置样例也是用包含关键词的形式触发的，但实际部署后发现并不能靠包含关键词触发？
即使是使用配置样例中的配置也不能够实现包含关键词回复的功能，也只能够在消息与配置中的关键词完全相符时触发回复。

**Comment by hundun000** [comment]
v0.2.2修复
