### ISSUE TITLE
有什么办法可以让阿米娅准点报时的时候顺带发一张表情包吗?

### ISSUE THREAD

**Issue by ConstantineQAQ** [hundun000/mirai-fleet-amiya#3]
rt，我想让阿米娅在准点报时的时候能随机发一张表情，顺便问问/阿米娅这个命令关键词可以改成/a吗

**Comment by hundun000** [comment]
`v0.7.0`支持准点报时发送固定表情，随机表情未来版本待定；支持修改`/阿米娅`;

**Comment by ConstantineQAQ** [comment]
具体怎么修改/阿米娅为/a呢

**Comment by hundun000** [comment]
> 具体怎么修改/阿米娅为/a呢

修改`config\具体插件id\proxyConfigRepository.json`里的`primaryName`

**Comment by hundun000** [comment]
`v0.8.1`支持随机发一张图片

> "IMAGE:name_0.png|name_1.png" 随机发送name_0.png或name_1.png中的一个
